name: Download Dumps Repository

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  download-dumps:
    runs-on: azu

    steps:
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          
      - uses: actions/checkout@v4
      
      - name: Clone dumps repository
        run: |
          git clone --depth 1 --branch pa1qxxx-user-15-AP3A.240905.015.A2-S931BXXU1AYB4-release-keys https://dumps.tadiphone.dev/dumps/samsung/pa1q.git dump
          sudo find dump/ -type l -delete
          sudo find dump/ -type d \( -name ".git" -o -name ".github" \) -exec rm -rf {} +
          
      - name: Upload dumps repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dumps-repository
          path: dump/
          retention-days: 30
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true
